#配置端口
server:
  port: 8077
spring:
  application:
    name: aircraft
  datasource:
    url: jdbc:mysql://localhost:3306/aircraft?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#配置mybatis-plus
mybatis-plus:
  #全局配置
  global-config:
    db-config:
      #配置主键生成策略：自动递增
      id-type: auto
  configuration:
    #关闭列名自动驼峰命名规则映射(驼峰自动转下划线)
    map-underscore-to-camel-case: false
    #开启SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'
