#配置rabbitmq
spring:
  rabbitmq:
    host: 192.168.66.200
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /
    #开启确认模式
    publisher-confirm-type: correlated
    #开启退回模式
    publisher-returns: true



#日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'