dubbo:
  application:
    # 应用名
    name: payment-service
  protocol:
    # 协议
    name: dubbo
    # 端口号 设置端口为 -1 表示 dubbo 自动扫描并使用可用端口（从20880开始递增），避免了端口冲突的问题。
    port: -1
  registry:
    address: nacos://192.168.66.128:8848

server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.150:3307/test?serverTimezone=UTC
    username: root
    password: 123456