#配置rabbitmq
spring:
  rabbitmq:
    host: 192.168.66.200
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /



#日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'