spring:
  application:
    name: skywalking-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.128:8848

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  port: 8003