server:
  port: 7777

spring:
  application:
    #应用名字
    name: cloud-sentinel-payment
  cloud:
    sentinel:
      transport:
        # Sentinel 控制台地址
        dashboard: 192.168.66.128:8688
        # 关闭context整合
      web-context-unify: false