spring:
  application:
    name: payment-service
  cloud:
    consul:
      # consul 服务地址
      host: 192.168.66.200
      # consul 服务端口
      port: 8500
      discovery:
        # 当前服务注册到consul的名字
        service-name: ${spring.application.name}
        # 注册时使用IP地址而不是hostname
        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?userUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
server:
  port: 8001