# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///student?serverTimezone=UTC
    username: root
    password: root


# mybatis配置
mybatis:
  # 映射文件位置
  mapper-locations: com/itbaizhan/springbootmybatis/mapper/*Mapper.xml
  # 别名
  type-aliases-package: com.itbaizhan.springbootmybatis.domain

#日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'