spring:
  application:
    name: order-consumer
  cloud:
    consul:
      host: 192.168.66.200
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

server:
  port: 80